services:
  - type: web
    name: ytwebapp
    env: python
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "uvicorn backend.main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: RECAPTCHA_token
        sync: false
